"""final model cleanup

Revision ID: 50d5e3f4da10
Revises: 8a9a860061d6
Create Date: 2025-05-03 03:12:37.675144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d5e3f4da10'
down_revision: Union[str, None] = '8a9a860061d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('media_type', sa.String(), nullable=True))
    op.drop_column('media', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('media', 'media_type')
    # ### end Alembic commands ###
