"""add agent to Session

Revision ID: 578fdb5bdb61
Revises: efc80cb21b5e
Create Date: 2025-05-03 02:42:07.345930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578fdb5bdb61'
down_revision: Union[str, None] = 'efc80cb21b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('session_data', sa.JSON(), nullable=True))
    op.add_column('sessions', sa.Column('agent', sa.String(), nullable=True))
    op.drop_column('sessions', 'message')
    op.drop_column('sessions', 'agent_name')
    op.drop_column('sessions', 'response')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('agent_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'agent')
    op.drop_column('sessions', 'session_data')
    # ### end Alembic commands ###
